version: "3.8"
services:
  scraper:
    build: .
    volumes:
      - ./:/app
  mongodb:
    image: mongo
    restart: always
    logging:
      driver: none
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: test
